013_Updated ReadMe files for Backend
sdagn1/TheExtraSemicolon_BackEnd pull request #5
Opened 2024-08-28 08:12 UTC by jemorak

2024-08-28 08:24 UTC, Adnanhoq approved these changes

2024-08-28 09:52 UTC, Leebee1392 approved these changes

2024-08-30 11:18 UTC, JennicaMistry requested changes

2024-08-30 11:18 UTC, JennicaMistry commented on README.md
> -export FLYWAY_USER="YOUR_DB_USERNAME"
You need both, DB_HOST for the Java application and FLYWAY_URL for your migrations

2024-08-30 11:24 UTC, Adnanhoq approved these changes

2024-08-30 13:27 UTC, Adnanhoq approved these changes

2024-08-30 13:50 UTC, JennicaMistry requested changes

2024-08-30 13:50 UTC, JennicaMistry commented on README.md
> -export FLYWAY_USER="YOUR_DB_USERNAME"
There should be two sections, one that has DB_HOST, username and password and another with FLYWAY_URL, username, password and migrate

2024-09-02 09:19 UTC, JennicaMistry approved these changes

2024-09-02 09:21 UTC, merged